before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: MR4bSOkBszibqlqEFtEBFUvD5HTMUlaEEtxawuhVJhmhcD0ZTbBmQCegNC3qe+fi3N9pwSb21vl1WZTkjwb7iUBNTo0zbEq58oEFcTxsbq6cc16BQlbRqUuZqNe5Q0pfHSQR0U8hKbczS4OtH9DjkUocQ4ZXzfq7rRSwuqPzM6tiN7FCSZVn0uOoXYArus9I0uM+ErCYuk7dPh6p4lQIKtdUjWbVhSWHBajQZAtIgJR+NODkk/G6GudXDYxF01kmjjzCDf14TpkcDZAi1qrguwE9ti0fPkvz4wEhmhXlLLdekmI9MVXNNhea87IjRjFp60Z5uQ80g4PTZ/vEipyRQDIfWAcQdqSiNAjExkqlhxu/MSZr0zcMOz5aeryPhkKNtaSK0cgQ8l7t8paXm1FhFmO9doM4CMKkMMna+ow9hmB0gLEYPoC6nhqJGv5REWFcsfWmzZT/Cm6KBqlDiT3eIwtC3AQOEycubSR0l3j6+tmtQNHPQ//N+uk7oCWd2693m2eyEMP8OmpuGm/pkcBls1rC6JtdouSSexP3U7g31F7rxgvuFjNpGlGOUl0aFffEAlgZvJlm8EyIBldkjpfYoisScZ4eH3Fh2uPK2IZUq7jVfujFL/INYC9xg80lesTe9CY6Om7ZLWjI5A68tXM5TlYyXUb8zsELD4ZDl1jW6IM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
